sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
python:
- '3.4'
cache:
  directories:
  - node_modules
before_install:
- echo $authfile | gpg --passphrase-fd 0 src/auth.json.gpg
- echo $datafile | gpg --passphrase-fd 0 src/data.json.gpg
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
  g++ python3.4
- npm install -g node-pre-gyp node-gyp
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- npm install sqlite --save
install:
- npm install
script:
- npm test
notifications:
  email: false
env:
  global:
  - secure: QnlEE7p8bW8Pqemy69k2Mh+Jgn0JR+LnWSEa+gmZhpxjNawiB4+7NKhOHZdL2dsdltaXlhlOhTlIwTILzxTPnmkJkUcLXCEih7kwj7pj56DMky8c0Se+pkaVMJEMYWIF0ni4Tv2a4LYfVfK4Prq/3UGdHP7TrWzz0vhOUJunBP8bXOVKTmSql6Pys3LNg2ls6IlJqMLV7YxH6vl/YMti1829EeP1z8bJ+Hoso+e5tnc+7ogMptQRq+xMuAgfL7HK1smbc3CRRz3usTu/LmO6RdIxECYf1O01b4glA0VlVzB1COk48wTErj+IDW5Eh9GuQDuPZpTr+z5sHK0PhW836DP7UDZpGPpDscFMNkyKA/I3fCi1iepycBZCYUEij9SweVQak969ORNZyU5J8ZjZJBNQPNIp6UhDRRrmK9JRi43pxhCiRLOkCblK74KXcPNYThySy8b+hj5HTgPzHqtF4VRMADikM5VFjCseoUhkAB1hTrohaxNNYlP5y7tOD5fObRIAMtLLsRDZTLqD8uWwDbJZ56LvN9Mx0IfWv5GdIyuSfzvx6fJz9sgGjZWrBRQnPd7o+RhPk8FT9pPyvgshGuPNGlprvaNkIENMYHwO8ImPii7KrYHX+/UOuaUMiUswZHL70KZVFmbPwEUzlmAFRRFGN1lT7tpytUfXxxJ5OIk=
  - secure: QIu6lJZYiIIXLYELW6LY+N5dMhdPlTlpVX3YDNbYm29gdtJptvRlMV6FxIQeIhTISBh7NnZF0jz/OSXeUarKtozTAP+cUOl9pYYAX/9fZwTOuhLTP7c+t5z7F7V5vZ2o/rzf0PHNiwyW2gM3+ltE5XvBFmKgm7DDEfFIgrQfsugl9GDDRvedsSQtXVU8Ap7OMGh3VFynCeYQKs3jDgHpggUONEi9TYgaLSdpxy9ey1rVjYxx+ZyFJbDDQslP5K6JwOrIc/G4SMzB85K68udy7lBkgRC4Z9LOKR3gZByogmcrOLEXR9x5N3J4gdz9CqwVYz05EYPfd98XwzEWbIL/fyWmdUO3OXLqGp4RWjcdNfGGs0oBN3NH2rG4Uc6jhTD/gU/pGYj3eY5CLTIX92WAS8qupDtkGOAccs53BJfpK+Xy85cS8nGrVX8/dE1AsWjldnd5nX4mEW3a0lfnPHnRTjWGP+OCCwyD4bU1EqXHHJd4Nkd0nzisvazz8WfpK52WM4u2xRVnz/VPMmyv3clCecgA+zWWZ8wMFM3ac2CjCCOwoT5ZYTi0XOJS2k+FMS2t6NE22um6bZDn8JzfwT/O5ZtG0JjOVuX3a3UqYFgTQc87wlbSItfcprkO7qKmOVt+JRzm+IGaSBpw5obR1wvuA9Udr8qRssIalCcSWwmRjkA=
