sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
python:
- '3.4'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_bcb16124b8a4_key -iv $encrypted_bcb16124b8a4_iv -in auth.json.enc -out src/auth.json -d
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ python3.4
- npm install -g node-pre-gyp node-gyp
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- npm install sqlite --save
script:
- npm start
notifications:
  email: false
