sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
python:
- '3.4'
cache:
  directories:
  - node_modules
before_install:
- echo $authfile | gpg --passphrase-fd 0 src/auth.json.gpg
- echo $datafile | gpg --passphrase-fd 0 src/data.json.gpg
- sudo apt-get update -y
- sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential
  g++ python3.4
- npm install -g node-pre-gyp node-gyp
- echo "alias python=python3" >> .bashrc
- source .bashrc
before_script:
- npm install sqlite --save
install:
- npm install
notifications:
  email: false
env:
  global:
  - secure: KhVcex5Q/w5SMKkiMnAFMuAso6fd60CoGzUpebFcSckijp0VhC2PTXxPyj2iZ4uYI/1R0h1XTyeB5E3XZFRCxVLihn36I5w8rhq92R0h88RdXl4+PiamoQFsqkLFbzUoGelv2F6T3qChDNy3ggLvOaWOOCYs3nEmKsM4149hHi24X7e0HkWdUnXfyMRKBkqWaPj14e4bnlKxYaYZowRB3OsTctyDmDXH2gkzs3kRKpPXyXPSTV0r3d/cjBkLq4pPYrT+7WrLpAscyijIg1jsc7AaYrzrOUxielSAtqZlusF/KUzhiwpAM/VUiuOgQ+ZPeqkEkcGIBf9jeirbY5JJ65OnxfvxZNdr2xqeFcWR+3dLTwUo05AO2Yj9xX3+hvlOk6qwKdISe8gkZoe+QkTwDXiqOVnnsPg5nUnjBUCFcO9KSy6eD5eVnTAFLoNqQOkJJCKpyk94kA2gAYhgh5/Td0RK4XNS78bDLaB3EN5c7UuuMQVLMTnVullCv0Yp0VqT/ujrAlQXq4ltpt7mE1aE8J26zhpaJCBTgM1Vh1kknawzXVH/x2lK3xgjnfh0bzf2VGYuxjfN0eeDoXis0l4jED072DI+GAaE+Q94AxhqAS1RUIJWa5kxKqCfFOrFceQuLVLiSKBZcc0Ou+zCo8SYNLdUG2jffx1xzYbTxoamdrM=
  - secure: ZazBrum+Dp1EGqPIelPYH3/qnf6pFV/Icb5zfNUkuDsEkputzaDjNWIcLJy/WyvAF1tc4iebCHoHj7d4i3R17llZuctO8CL6UizpRpHov8W725vM01HN0Aiq3Ck6aENWbq086cv0JJGvxI30X6VjZUxiOEKMWEh1c3hR5Z0sSzteuDO9pqgHEacYTgAo5CnZ2JtReTMokSGNZZGKU3u0ElhZffJ4ajxpAkwasDn+4bOme5EbltKD+eH54Uv70krX1nBRyRRfM1OlTTcGg6PetFNJ0laHTkdY6GYrBUKNjgb7yS0LufOhigQIpxFGCQsV9Xnc2ev2DpoA8N7cDbzQlAVMlTszvtWT4nVV5gt0i7RN6zjmbMPfJTx8RxwLXTYL3SxLLfMVXryEUtahpFD/T2t56JGHRrRjiUvVPYqvGXxG0JI4uRcwhEAXiSF8POnyChTvkCDDS7gMDwTnMGaNRL/LQ2m7mttXUa2UDgQUFWJhh3EKkqpaveOgX0RlowllgjvKH9AnG2uV8IOYq61Gpuku+wtYWfCCw1Lg9ui5ZXg2hYPQBUBvEiKy3zwvsp/CCyAxkF/uRTq40JGQMfQPbR0QFcZZgE0vYvgnkVQvb0M6ZpDPyJxD0sH+6p/fjg0bEp5GNu41qhZ3uy0D5eXe8LwZMioADXWz5gDDc+y/EOg=
