sudo: required
dist: trusty
os: linux
language: node_js
node_js:
- '8'
before_script:
- sudo apt-get install -y build-essential
- npm install -g node-pre-gyp node-gyp 
- npm install
script:
- npm start
cache:
 directories:
 - "node_modules"